on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # This allows manual triggering

  schedule:
    - cron: '* * * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3'] # It's good practice to be more specific with PHP versions
    name: integration-tests (PHP ${{ matrix.php-versions }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated from v1

      - name: Install PHP
        uses: shivammathur/setup-php@v2 # v2 is a stable major version, ensure it's the one you intend.
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, json, zip # Add common extensions if your project needs them
          tools: composer:v2 # Optionally specify composer version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT # Updated way to set output

      - name: Cache Composer dependencies
        uses: actions/cache@v4 # Updated from v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Consider making the key more specific for PHP version if dependencies change significantly
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress --no-interaction # Added --no-interaction for CI

      - name: Run script
        run: |
          php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ${{ secrets.OCI_PRIVATE_KEY_FILENAME }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_SHAPE: ${{ secrets.OCI_SHAPE }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          AD_ALWAYS_FREE: ${{ secrets.AD_ALWAYS_FREE }}
          TEST_IMAGE_ID: ${{ secrets.TEST_IMAGE_ID }}
          TEST_SUBNET_ID: ${{ secrets.TEST_SUBNET_ID }}
